### ISSUE TITLE
GitHub

### ISSUE THREAD

**Issue by lisablank1** [datascience-mobi/2021-topic-03-team-01#2]
Hi, ich glaube ich habe aus Versehen mehr als nur ein aktualisiertes Dokument gepusht, sondern anscheinend einen ganzen Ordner (102 files laut der Code Seite :0). Wie kann ich das denn wieder rückgängig machen? Ich wollte eigentlich nur das aktualisierte Data sorted and ordered.Rmd pushen...

**Comment by leoniethomas** [comment]
Hey, das liegt daran, dass ihr im Moment wenn ihr was pushed alle Veränderungen pushed die in dem Folder gemacht werden. Die Files die du da gepushed hast sind, so wie es aussieht files die durch das Rproj was du erstellt hast entstehen. Es kann auch gut sein, dass du die in deinem Foldersystem nicht siehst weil dort in der default Einstellung files die mit einem Punkt beginnen nicht angezeigt werden. Die Lösung hierzu ist ein .gitignore file zu erstellen.

**Comment by leoniethomas** [comment]
Lest euch das mal durch, wenn euch dass nicht weiterbringt fragt einfach nochmal :)
https://www.pluralsight.com/guides/how-to-use-gitignore-file

**Comment by leoniethomas** [comment]
und die Daten sind vertraulich und sollten daher nicht auf einem öffentlich zugängigen repo hochgeladen werden also entfernt das in mit dem gitignore file bitte auch aus dem repo

**Comment by lisablank1** [comment]
wie entferne ich das aktuell gepushte denn? oder welche Daten meintest du genau soll ich wieder entfernen? Sorry, GitHub ist noch ein wenig ein Mysterium für mich ..

**Comment by lisablank1** [comment]
also erstelle ich jetzt ein normales textfile mit den entsprechenden Befehlen und pushe dieses File (.gitignore) dann ins repository?

**Comment by leoniethomas** [comment]
Kein Problem, dafür ist das Projekt ja da, dass ihr lernt wie man damit umgeht und so :)  Ja genau das ist ein Text file das du auf deinem Computer lokal schreibst und dann in den ordner auf deinem Computer reinkopierst, wenn du dann das nächste mal ein commit machst weis git dass es die files die in dem .gitignore aufgelistet sind ignorieren soll. Gruppen 3 und 4 haben so ein file auch bereits also wenn es nicht funktioniert können euch  auch eure Komulitonen helfen :)
