### ISSUE TITLE
verschiedene Normalisierungen 

### ISSUE THREAD

**Issue by lisablank1** [datascience-mobi/2021-topic-03-team-01#4]
Hi Leonie, 
wir haben uns zusammengesetzt und versucht die Normalisierung nach deinen Anweisungen zu überarbeiten.
Wir haben mehrere Varianten ausprobiert:
Auf den Bildern links ist das Protein nach der entsprechenden Normalisierung, rechts (grün) die ursprüngliche Verteilung des korrespondierenden Proteins. 

1. Normalisierung eines Proteins über die 3 Replikate einer Fraktion (d.h. Fraktionsweise und Proteinweise in einem code kombiniert)
![Screenshot (170)](https://user-images.githubusercontent.com/82637948/118853671-48ddb900-b8d4-11eb-845d-384c294b703d.png)

2. Normalisierung fraktionsweise über alle Proteine zusammen
![Screenshot (172)](https://user-images.githubusercontent.com/82637948/118854241-e1743900-b8d4-11eb-9097-0e05bffd7e4c.png)

3. Normalisierung erst proteinweise (unser ursprünglicher Code), dann fraktionsweise (2 mal der loop) (hat nicht geklappt)

4. Normalisierung erst fraktionsweise, dann proteinweise (2 mal der loop) 
![Screenshot (171)](https://user-images.githubusercontent.com/82637948/118853907-90fcdb80-b8d4-11eb-9484-6a523d463a99.png)

Hier zum Vergleich nochmal unsere ursprüngliche Idee (nur proteinweise):
![Screenshot (173)](https://user-images.githubusercontent.com/82637948/118854493-13859b00-b8d5-11eb-83ee-80b9976f8057.png)

Unsere Meinung: nur bei der proteinweisen Normalisierung bleibt die Form der Kurve gleich. So wie wir es verstanden haben ist das auch sinnvoll.
Die Kurvenform variiert vor allem bei den kombinierten Varianten, die Maxima sind komplett anders als in den Originaldaten. 
Da wir am Ende des Projektes auch nur pro Protein vergleichen, ob die Maxima in Ctrl und RNase variieren halten wir es für sinnvoll die Normalisierung proteinweise zu machen, da die Proteine untereinander ja nicht verglichen werden. Die Menge an Protein 1 in Fraktion 1 hat nicht unbedingt etwas mit der Menge an Protein 2000 in Fraktion 1 zu tun.

Meinst du, dass die kombinierte Variante immer noch die beste ist, auch wenn die Kurvenform am meisten von den Originaldaten abweicht? Oder können wir bei der proteinweisen Normalisierung bleiben?

Danke schonmal und liebe Grüße,
Lisa, Tyra, Emma, Nina

**Comment by leoniethomas** [comment]
Hey, ja dass eure Kurvenverläufe so unterschiedlich sind, sollte nicht so sein. Vielleicht reden wir am Mittwoch nochmal darüber, was genau ihr gemacht habt um zu schauen, warum eure Kurven nach der Normalisierung so komisch aussehen. Ja dann bleibt erstmal  bei eurer eigentlichen Methode, wenn die am besten aussieht :)
