### ISSUE TITLE
y-shift mit den 3 reps

### ISSUE THREAD

**Issue by lisablank1** [datascience-mobi/2021-topic-03-team-01#5]
Wenn wir nun alle 3 Reps benutzen, wie bestimmen wir dann den y-shift? 
Vergleichen wir dann Ctrl Rep 1 mit allen 3 Reps der RNase, bilden aus den Differenzen den Mittelwert und schauen dann, ob der y-shift mit diesem Mittelwert signifikant ist?
Und dann ebenso für RNase Rep 1 mit Ctrl Rep1-3 ? Oder reicht es aus wenn wir nur von der Ctrl ausgehen?

**Comment by leoniethomas** [comment]
![image](https://user-images.githubusercontent.com/49941230/121393487-ace22300-c950-11eb-9937-f45203f04d55.png)
Die mean difference bekommt ihr von dem t.test gegeben. Also ihr macht nen ttest. Dabei ist der input x die 3 y-Werte (protein amount) von der ctrl und der input y die 3 y-Werte (protein amount) von der rnase sind. Also macht ihr einen ttest auf den protein amount in einer fraction. Und als output bekommt ihr ja auch einen estimates der means, daraus könnt ihr ja dann den shift berechnen

**Comment by lisablank1** [comment]
Alles klar, dann würde uns aber der p-Wert, den wir daraus bekommen, bereits sagen ob ein signifikanter shift vorliegt, oder nicht? Oder müssen wir anderweitig überprüfen, ob dieser signifikant ist?

**Comment by leoniethomas** [comment]
Das ist auch ein Punkt der sich durch das gausfitting erledigt, da ihr dann für alle 3 replikate die Maxima ausgegeben bekommt. 
Da ihr das ja nicht macht würde ich die Werte der replikate welche an der Fraktion kein Maximum haben trotzdem einsetzen.
