### ISSUE TITLE
x-shift mit mehr als einem Maximum

### ISSUE THREAD

**Issue by lisablank1** [datascience-mobi/2021-topic-03-team-01#6]
Hi Leonie :)
wir haben heute den y-shift fertig gemacht und auch den x-shift für die Proteine gemacht, die nur 1 Maximum in Ctrl und RNase haben.
Wir wissen jetzt aber nicht, wie wir mit den ca. 600 Proteinen umgehen sollen, die mehr als 1 Maximum haben. 
Woher wissen wir, welche Maxima wir miteinander vergleichen sollen? Wir können ja schlecht für jedes Protein einzeln die Verteilung anschauen, oder?
Hast du hier einen Ratschlag für uns?
Danke schonmal und schönes Wochenende:)

**Comment by leoniethomas** [comment]
Hey Lisa, 
ich würde einfach alle möglichen Shifts betrachten:)
